### ISSUE TITLE
Fuel Cans don't work

### ISSUE THREAD

**Issue by Aviradim** [WazeDevil/bug-tracker#5]

**Comment by Aviradim** [comment]
cdn-fuel btw

**Comment by WazeDevil** [comment]
Fixed!
![image](https://github.com/WazeDevil/bug-tracker/assets/106198964/5434a43c-9c25-4fe1-b74d-4fa2d27a94dd)
![image](https://github.com/WazeDevil/bug-tracker/assets/106198964/139e5552-4bad-479f-8de2-f16cb104c450)
